#!/bin/bash



zotero() {
    wget -qO- https://raw.githubusercontent.com/retorquere/zotero-deb/master/install.sh | sudo bash
    sudo apt -y update
    sudo apt -y install zotero
}

sudo snap -y remove firefox

sudo snap install terminal-parrot discord spotify pulseeffects


# install flatpak
sudo apt install -y flatpak
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install -y flathub md.obsidian.Obsidian 
flatpak install -y flathub net.nokyan.Resources
flatpak install -y flathub org.mozilla.firefox
