#!/bin/bash

docker() {
  # Add Docker's official GPG key:
  sudo apt update
  sudo apt install ca-certificates curl
  sudo install -m 0755 -d /etc/apt/keyrings
  sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  sudo chmod a+r /etc/apt/keyrings/docker.asc

  # Add the repository to Apt sources:
  echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  sudo apt update


  sudo apt install docker-ce docker-ce-cli containerd.io

  sudo usermod -aG docker $USER
  sudo systemctl enable docker && sudo systemctl start docker
}


vscode() {
  sudo apt install software-properties-common apt-transport-https wget
  wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
  sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
  sudo apt update
  sudo apt install code
}

zoxide() {
  curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/ajeetdsouza/zoxide/master/install.sh | bash
  echo "eval $(zoxide init --cmd cd bash)" >> ~/.bashrc
}


nvm() {
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
  nvm install 18
}

slack() {
  wget https://downloads.slack-edge.com/linux_releases/slack-desktop-4.19.2-amd64.deb
  sudo apt install ./slack-desktop-4.19.2-amd64.deb
}

mkdir -p ~/tmp && cd ~/tmp

docker && vscode && zoxide && nvm && slack




read -p "Do you want to reboot the system? (y/n): " answer
if [[ $answer == "y" ]]; then
  reboot
fi
