#!/bin/bash


$PWD=$(pwd)

cd ~
touch .inputrc

echo '"\e[1;6C": kill-word' >> .inputrc
echo '"\e[1;61D": backward-kill-word' >> .inputrc
echo '"\e[1;2C": delete-char' >> .inputrc
echo '"\e[1;2D": backward-delete-char' >> .inputrc
echo '"\C-H": backward-kill-word' >> .inputrc
echo 'eval "$(zoxide init --cmd cd bash)"' >> ~/.bashrc


git config --global credential.helper store
git config --global user.email heofthetea@gmail.com
git config --global user.name heofthetea

if [ ! -z $("which guake") ]; then
	guake --restore-preferences "$PWD/dotfiles/.guakerc"
fi

mkdir -p "~/.config/terminator/config" && cp "$PWD/dotfiles/.terminatorrc" "~/.config/terminator/config"
